apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenithr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zenithr-operator
  template:
    metadata:
      labels:
        name: zenithr-operator
    spec:
      serviceAccountName: zenithr-operator
      containers:
        - name: zenithr-operator
          # Replace this with the built image name
          image: quay.io/kiegroup/zenithr-operator
          command:
          - zenithr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zenithr-operator"
